Image component
KoushikKintali/NaN-UI pull request #11
Opened 2022-02-25 04:22 UTC by KoushikKintali

2022-02-27 17:18 UTC, sanathkumar26700 approved these changes

2022-03-04 09:25 UTC, dev-prabhat requested changes
CSS classes are relevant what it meant to be just remove those inline styles

2022-03-04 09:25 UTC, dev-prabhat commented on components/image/image.html
> +                        style="width: 100%; height: 95px; border:0; transform: scale(1); overflow:hidden;"
remove inline style

2022-03-04 09:25 UTC, dev-prabhat commented on components/image/image.html
> +                        style="width: 100%; height: 95px; border:0; transform: scale(1); overflow:hidden;"
same inline style

2022-03-06 10:54 UTC, MonikaJhingan approved these changes
You can avoid using inline styling in upcoming projects rest the code looks good to be merged.

2022-03-06 15:15 UTC, merged